-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 09:46:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema club
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `club` ;
USE `club` ;

-- -----------------------------------------------------
-- Table `club`.`Verein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club`.`Verein` (
  `idVerein` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Tabellenplatz` INT NULL,
  PRIMARY KEY (`idVerein`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`Trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club`.`Trainer` (
  `idTrainer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Verein_idVerein` INT NOT NULL,
  PRIMARY KEY (`idTrainer`),
  INDEX `fk_Trainer_Verein1_idx` (`Verein_idVerein` ASC) VISIBLE,
  CONSTRAINT `fk_Trainer_Verein1`
    FOREIGN KEY (`Verein_idVerein`)
    REFERENCES `club`.`Verein` (`idVerein`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`Spieler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club`.`Spieler` (
  `idSpieler` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Trainer_idTrainer` INT NOT NULL,
  `Verein_idVerein` INT NOT NULL,
  PRIMARY KEY (`idSpieler`),
  INDEX `fk_Spieler_Trainer_idx` (`Trainer_idTrainer` ASC) VISIBLE,
  INDEX `fk_Spieler_Verein1_idx` (`Verein_idVerein` ASC) VISIBLE,
  CONSTRAINT `fk_Spieler_Trainer`
    FOREIGN KEY (`Trainer_idTrainer`)
    REFERENCES `club`.`Trainer` (`idTrainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spieler_Verein1`
    FOREIGN KEY (`Verein_idVerein`)
    REFERENCES `club`.`Verein` (`idVerein`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
